### ISSUE TITLE
Please provide arm package as well to support Apple M1 

### ISSUE THREAD

**Issue by spider-network** [hypnoglow/terraform-provider-oryhydra#10]
Unfortunately, some of us can no longer use the module because there is no ARM package. Would it be possible to provide these as well?

<img width="581" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/13738/161632096-5287ca87-3397-4fd3-a4f5-b44055a00198.png">

**Comment by spider-network** [comment]
@hypnoglow Is it possible to compile also apple m1 binaries?

**Comment by hypnoglow** [comment]
Available in v0.4.0 release.
