### ISSUE TITLE
Support providing an Authorization Header manually

### ISSUE THREAD

**Issue by davearata-snorack** [hypnoglow/terraform-provider-oryhydra#9]
The authentication method that protects our hydra admin API is not a standard OAuth 2.0 credentials flow. However we can generate a token through our terraform and then provide the token in authorization header for hydra. A potential example below
```
data "google_service_account_id_token" "oidc" {
  target_audience = "https://your.hydra.admin.app/"
}

provider "oryhydra" {
  url = "https://your.hydra.admin.app"
  authorization_header = "Bearer ${data.google_service_account_id_token.oidc.id_token}"
}
```

**Comment by hypnoglow** [comment]
I've released prerelease version `v0.5.0-pre.0` with this feature included, let me know if it works for you.
